import { ProjectItem } from "@/types/projects/types";

export const projects: ProjectItem[] = [
    {
        id: "blockchain-traceability",
        title: "DrugTrace Ledger Network",
        description: "Designed and developed a permissioned blockchain solution for end-to-end drug traceability across manufacturers, distributors, pharmacies, and regulators using Hyperledger Fabric and Spring Boot.",
        image: "/projects/blockchain.png",
        tech: ["Hyperledger Fabric", "Go", "Spring Boot", "Open Policy Agent"],
        github: "https://github.com/nguyentienphat2904",
        featured: true,
        wide: true,
    },
    {
        id: "jira-clone",
        title: "Jira Mobile Native",
        description: "Built a robust cross-platform mobile application replicating core Jira task management, workflow tracking, and notifications using React Native and Figma design patterns.",
        image: "/projects/jira_mobile.png",
        tech: ["React Native", "Figma", "Redux", "Sentry"],
        github: "https://github.com/nguyentienphat2904",
        featured: true,
        wide: false,
    },
    {
        id: "fhir-healthcare",
        title: "HL7 FHIR Healthcare Engine",
        description: "Implemented full-stack HL7 FHIR configuration management modules with versioning and mapping configuration workflows for healthcare platforms.",
        image: "/projects/fhir_health.png",
        tech: ["NextJS", "NestJS", "Prisma", "PostgreSQL"],
        github: "https://github.com/nguyentienphat2904",
        featured: false,
    },
    {
        id: "corporate-cms",
        title: "Corporate Web & CMS",
        description: "A freelance business website featuring server-side rendering (SSR), search engine optimization (SEO), and a custom administrative content management panel.",
        image: "/projects/corporate.png",
        tech: ["Next.js", "React", "Tailwind CSS", "MongoDB"],
        link: "https://tiendungcorp.com",
        github: "https://github.com/nguyentienphat2904",
        featured: false,
    },
    {
        id: "access-gateway",
        title: "Enterprise Access Gateway",
        description: "Developed RESTful backend access control solutions using Spring Boot, integrating dynamic authorization policies with Open Policy Agent (OPA).",
        image: "/projects/gateway.png",
        tech: ["Spring Boot", "Open Policy Agent", "Spring Security"],
        github: "https://github.com/nguyentienphat2904",
        featured: false,
    },
];